addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.0")
//addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "6.5.0")
addSbtPlugin("au.com.onegeek" % "sbt-dotenv" % "2.1.204")
