name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Scala
      uses: olafurpg/setup-scala@v2
    - name: Run tests
      run: sbt test
    - name: Run ittest
      run: sbt it:test
